language: android
android:
  components:
    - android-28

addons:
  sonarcloud:
    organization: "nguyen-darianhuy-github"

script:
  - ./gradlew build connectedCheck 
  - sonar-scanner -Dsonar.verbose=true -X
