language: android
android:
  components:
    - build-tools-28.0.3
    - android-28
    - sys-img-x86-android-28

addons:
  sonarcloud:
    organization: "nguyen-darianhuy-github"

script:
  - ./gradlew build connectedCheck
  - sonar-scanner -Dsonar.verbose=true -X
