CREATE TABLE Login (
	Username VARCHAR(50) NOT NULL,
	Password VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	PRIMARY KEY (Username)
);

CREATE TABLE User (
	UserID INTEGER NOT NULL AUTO_INCREMENT,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	Username VARCHAR(50) NOT NULL,
	Bio VARCHAR(500),
	Age INTEGER,
	PRIMARY KEY (UserID),
	FOREIGN KEY (Username) REFERENCES Login(Username)
);

CREATE TABLE TripListing (
	RideID INTEGER NOT NULL AUTO_INCREMENT,
	DriverID INTEGER NOT NULL,
	MaxPassengers INTEGER NOT NULL,
	NumPassengers INTEGER NOT NULL,
	Destination VARCHAR(255) NOT NULL,
	Departure VARCHAR(255) NOT NULL,
	PostDate DATE NOT NULL,
	DepartureDate DATE NOT NULL,
	PRIMARY KEY (RideID),
	FOREIGN KEY (DriverID) REFERENCES User(UserID)
);

CREATE TABLE RidePassengers {
    RideID INTEGER NOT NULL,
    PassengerID NOT NULL,
    FOREIGN KEY (RideID) REFERENCES TripListing(RideID),
    FOREIGN KEY (PassengerID) REFERENCES User(UserID)
};

CREATE TABLE Rating (
	RatingID INTEGER NOT NULL AUTO_INCREMENT,
	ReviewedID INTEGER NOT NULL,
	ReviewerID INTEGER NOT NULL,
	Rating INTEGER NOT NULL CHECK (Rating between 1 and 5),
	Comment VARCHAR(500) NOT NULL,
	PRIMARY KEY (RatingID),
	FOREIGN KEY (ReviewedID) REFERENCES User(UserID)
	FOREIGN KEY (ReviewerID) REFERENCES User(UserID)
);
